-- ============================================
-- SQL Update for Manager-Employee Hierarchy
-- ============================================
-- Run this in the Supabase SQL Editor to enforce strict data isolation.

-- 1. DROP EXISTING POLICIES (to avoid conflicts)
DROP POLICY IF EXISTS "Users visibility" ON users;
DROP POLICY IF EXISTS "Tokens visibility" ON tokens;
DROP POLICY IF EXISTS "Form entries visibility" ON form_entries;
DROP POLICY IF EXISTS "Token updates" ON tokens;
DROP POLICY IF EXISTS "Entry updates" ON form_entries;

-- 2. USERS TABLE POLICY
-- Managers can ONLY see:
--  a) Themselves
--  b) Employees they added (added_by = auth.uid())
CREATE POLICY "Users visibility" ON users
  FOR SELECT USING (
    id = auth.uid() OR              -- See self
    added_by = auth.uid()           -- See my employees
  );

-- 3. TOKENS TABLE POLICY
-- Managers can see tokens where:
--  a) They generated them (though managers don't usually generate tokens)
--  b) The token was generated by one of their employees
CREATE POLICY "Tokens visibility" ON tokens
  FOR SELECT USING (
    generated_by = auth.uid() OR
    generated_by IN (
      SELECT id FROM users WHERE added_by = auth.uid()
    )
  );

-- Managers can update tokens from their employees
CREATE POLICY "Token updates" ON tokens
  FOR UPDATE USING (
    generated_by = auth.uid() OR
    generated_by IN (
      SELECT id FROM users WHERE added_by = auth.uid()
    )
  );

-- 4. FORM ENTRIES TABLE POLICY
-- Managers can see entries where:
--  a) The entry belongs to one of their employees
CREATE POLICY "Form entries visibility" ON form_entries
  FOR SELECT USING (
    employee_id IN (
      SELECT id FROM users WHERE added_by = auth.uid()
    ) OR
    employee_id = auth.uid() -- Just in case a manager makes an entry
  );

-- Managers can update entries from their employees
CREATE POLICY "Entry updates" ON form_entries
  FOR UPDATE USING (
    employee_id IN (
      SELECT id FROM users WHERE added_by = auth.uid()
    ) OR
    employee_id = auth.uid()
  );

-- ============================================
-- Update Complete
-- ============================================
