-- ============================================
-- Migration 017: Fix Token Center Visibility
-- ============================================
-- Problem: Tokens generated by one user are NOT visible to other
--          users in the same center because:
--
--   1. The SELECT/UPDATE RLS policies from migration 013 required
--      role = 'owner' to see tokens from other users.
--      Migration 016 attempted to fix this but may not have been
--      applied, or 013 may have been re-run after it.
--
--   2. The frontend was NOT setting center_id when inserting tokens,
--      so all tokens had center_id = NULL — the center-based RLS
--      match (center_id = get_my_center_id()) never matched.
--
-- Fix:
--   A. Drop and recreate SELECT/UPDATE/INSERT policies so that ANY
--      authenticated user in the center can see and use ALL tokens
--      in that center.
--   B. Backfill center_id on existing tokens where it is NULL.
-- ============================================

-- ============================================
-- A. DROP EXISTING TOKEN POLICIES
-- ============================================
DROP POLICY IF EXISTS "Tokens visibility" ON tokens;
DROP POLICY IF EXISTS "Token updates" ON tokens;
DROP POLICY IF EXISTS "Anyone can generate tokens" ON tokens;

-- ============================================
-- B. SELECT — Center-wide visibility
-- ============================================
-- Any authenticated user can see:
--   • Tokens they generated (always)
--   • ALL tokens in their center (regardless of role)
CREATE POLICY "Tokens visibility" ON tokens
  FOR SELECT USING (
    generated_by = auth.uid()
    OR (
      center_id IS NOT NULL
      AND center_id = get_my_center_id()
    )
  );

-- ============================================
-- C. INSERT — Anyone authenticated can generate tokens
-- ============================================
-- The generated_by must match the caller. center_id is set by
-- the frontend (from the user's profile).
CREATE POLICY "Anyone can generate tokens" ON tokens
  FOR INSERT WITH CHECK (
    generated_by = auth.uid()
  );

-- ============================================
-- D. UPDATE — Center-wide update access
-- ============================================
-- Any user in the center can mark a token as used/cancelled.
-- This is needed so Employee B can use a token generated by
-- Employee A or the Owner.
CREATE POLICY "Token updates" ON tokens
  FOR UPDATE USING (
    generated_by = auth.uid()
    OR (
      center_id IS NOT NULL
      AND center_id = get_my_center_id()
    )
  );

-- ============================================
-- E. BACKFILL — Set center_id on existing tokens
-- ============================================
-- Any token that was inserted WITHOUT center_id gets the
-- center_id of the user who generated it.
UPDATE tokens
SET center_id = u.center_id
FROM users u
WHERE tokens.generated_by = u.id
  AND tokens.center_id IS NULL
  AND u.center_id IS NOT NULL;

-- ============================================
-- Verification:
--   1. Log in as any employee.
--   2. Run: SELECT * FROM tokens WHERE center_id = '<your_center_id>';
--   3. You should see ALL tokens from every user in your center.
-- ============================================
